# Generated by Django 3.2.9 on 2021-12-14 08:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductSystem', '0001_initial'),
        ('GeneralModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDeliveryForm',
            fields=[
                ('demo_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Belge Id')),
                ('reference_number', models.CharField(help_text="Referans numarasini 'MM(ADINIZ)-(6 haneli tarih: GGAAYY)-(BELGE NO)' seklinde giriniz.", max_length=20, validators=[django.core.validators.RegexValidator(message='Girmis oldugunuz referans numarasi uygun formatta degildir! (Ornek format: MMTYFN-010121-001)', regex='^MM[A-Z]{2,8}-[0-9]{6}-[0-9]{3}$')], verbose_name='Referans Numarasi')),
                ('log_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Tarih')),
                ('delivery_address', models.TextField(verbose_name='Teslim Adresi')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firm', verbose_name='Musteri')),
                ('client_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firmauthorizedperson', verbose_name='Ilgili')),
                ('product_id', models.ManyToManyField(to='ProductSystem.ProductIdentification', verbose_name='Urun Bilgisi')),
            ],
            options={
                'verbose_name': 'Demo Teslim Formu',
                'verbose_name_plural': 'Demo Teslim Belgeleri',
            },
        ),
        migrations.CreateModel(
            name='DeviceDeliveryForm',
            fields=[
                ('device_delivery_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Belge Id')),
                ('reference_number', models.CharField(help_text="Referans numarasini 'MM(ADINIZ)-(6 haneli tarih: GGAAYY)-(BELGE NO)' seklinde giriniz.", max_length=20, validators=[django.core.validators.RegexValidator(message='Girmis oldugunuz referans numarasi uygun formatta degildir! (Ornek format: MMTYFN-010121-001)', regex='^MM[A-Z]{2,8}-[0-9]{6}-[0-9]{3}$')], verbose_name='Referans Numarasi')),
                ('log_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Tarih')),
                ('delivery_address', models.TextField(verbose_name='Teslim Adresi')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firm', verbose_name='Musteri')),
                ('client_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firmauthorizedperson', verbose_name='Ilgili')),
            ],
            options={
                'verbose_name': 'Cihaz Teslim Formu',
                'verbose_name_plural': 'Cihaz Teslim Belgeleri',
            },
        ),
        migrations.CreateModel(
            name='RMAForm',
            fields=[
                ('rma_form_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Belge Id')),
                ('rma_number', models.CharField(help_text="RMA numarasini 'RMA(ADINIZ)-(6 haneli tarih: GGAAYY)-(BELGE NO)' seklinde giriniz.", max_length=20, validators=[django.core.validators.RegexValidator(message='Girmis oldugunuz RMA numarasi uygun formatta degildir! (Ornek format: RMATYFN-010121-001', regex='^RMA[A-Z]{2,8}-[0-9]{6}-[0-9]{3}$')], verbose_name='RMA Numarasi')),
                ('log_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Tarih')),
                ('entry_description', models.TextField(verbose_name='Aciklama')),
                ('entry_analysis', multiselectfield.db.fields.MultiSelectField(choices=[('hasarli_govde', 'Hasarli Govde'), ('hasarli_psu', 'Hasarli PSU'), ('hasarli_io_port', 'Hasarli I/O | Port'), ('hasarli_ekran_lcd', 'Hasarli Ekran | LCD'), ('hasarli_tus', 'Hasarli Tus'), ('diger', 'Diger')], max_length=77, verbose_name='Inceleme')),
                ('other_chechked', models.CharField(max_length=500, verbose_name='Tanim')),
                ('entry_note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('rma_description', models.TextField(blank=True, null=True, verbose_name='Aciklama')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firm', verbose_name='Musteri')),
                ('client_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firmauthorizedperson', verbose_name='Ilgili')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductSystem.inventory', verbose_name='Urun Girisi')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductSystem.productoutlet', verbose_name='Urun Cikisi')),
            ],
            options={
                'verbose_name': 'RMA Formu',
                'verbose_name_plural': 'RMA Belgeleri',
            },
        ),
        migrations.CreateModel(
            name='DeviceDeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_duration', models.CharField(max_length=1000, verbose_name='Teslim Süresi')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adet')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.devicedeliveryform', verbose_name='Form Id')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductSystem.inventory', verbose_name='Ürün Adi')),
                ('product_specifications', models.ManyToManyField(to='ProductSystem.ProductIdentification', verbose_name='Bilgiler')),
            ],
            options={
                'verbose_name': 'Cihaz Teslim Ürünü',
                'verbose_name_plural': 'Cihaz Teslim Ürünleri',
            },
        ),
        migrations.CreateModel(
            name='DemoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_duration', models.CharField(max_length=1000, verbose_name='Demo Süresi')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adet')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.demodeliveryform', verbose_name='Form Id')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductSystem.inventory', verbose_name='Ürün Adi')),
                ('product_specifications', models.ManyToManyField(to='ProductSystem.ProductIdentification', verbose_name='Bilgiler')),
            ],
            options={
                'verbose_name': 'Demo Ürünü',
                'verbose_name_plural': 'Demo Ürünleri',
            },
        ),
    ]
