# Generated by Django 3.2.9 on 2021-11-15 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeneralModel', '0004_deliverycompany'),
        ('ProductSystem', '0069_auto_20211115_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDeliveryForm',
            fields=[
                ('device_delivery_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Cihaz Teslim Id')),
                ('reference_number', models.CharField(max_length=20, verbose_name='Referans Numarasi')),
                ('log_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Tarih')),
                ('delivery_address', models.TextField(verbose_name='Teslim Adresi')),
                ('return_date', models.DateTimeField(verbose_name='Dönüs Tarihi')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firm', verbose_name='Musteri')),
                ('client_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firmauthorizedperson', verbose_name='Ilgili')),
                ('product_id', models.ManyToManyField(to='ProductSystem.Inventory', verbose_name='Urun Bilgisi')),
            ],
            options={
                'verbose_name': 'Cihaz Teslim Formu',
                'verbose_name_plural': 'Cihaz Teslim Belgeleri',
            },
        ),
        migrations.CreateModel(
            name='DemoDeliveryForm',
            fields=[
                ('demo_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Demo Teslim Id')),
                ('reference_number', models.CharField(max_length=20, verbose_name='Referans Numarasi')),
                ('log_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Tarih')),
                ('delivery_address', models.TextField(verbose_name='Teslim Adresi')),
                ('demo_duration', models.CharField(max_length=1000, verbose_name='Demo Süresi')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firm', verbose_name='Musteri')),
                ('client_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModel.firmauthorizedperson', verbose_name='Ilgili')),
                ('product_id', models.ManyToManyField(to='ProductSystem.Inventory', verbose_name='Urun Bilgisi')),
            ],
            options={
                'verbose_name': 'Demo Teslim Formu',
                'verbose_name_plural': 'Demo Teslim Belgeleri',
            },
        ),
    ]
