# Generated by Django 3.2.9 on 2021-11-15 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demodeliveryform',
            name='reference_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Yanlis format', regex='^MM[A-Z]{2,8}-[0-9]{6}-[0-9]{3}$')], verbose_name='Referans Numarasi'),
        ),
    ]
