# Generated by Django 3.2.9 on 2021-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0005_auto_20211115_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demodeliveryform',
            name='demo_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Belge Id'),
        ),
        migrations.AlterField(
            model_name='devicedeliveryform',
            name='device_delivery_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Belge Id'),
        ),
    ]
