# Generated by Django 3.2.9 on 2021-11-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0069_auto_20211115_1417'),
        ('Document', '0006_auto_20211115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demodeliveryform',
            name='product_id',
            field=models.ManyToManyField(to='ProductSystem.ProductIdentification', verbose_name='Urun Bilgisi'),
        ),
        migrations.AlterField(
            model_name='devicedeliveryform',
            name='product_id',
            field=models.ManyToManyField(to='ProductSystem.ProductIdentification', verbose_name='Urun Bilgisi'),
        ),
    ]
