# Generated by Django 3.2.9 on 2021-11-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0010_auto_20211122_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demoproduct',
            options={'verbose_name': 'Demo Ürünü', 'verbose_name_plural': 'Demo Ürünleri'},
        ),
    ]
