# Generated by Django 3.1.7 on 2021-08-02 13:30

import Finance.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Ödeme ID')),
                ('payment_code', models.CharField(default=Finance.models.AdvancePayment.generate_unique_code, max_length=8, verbose_name='Avans Kodu')),
                ('user', models.CharField(choices=[('betul-admin', 'betul-admin'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-admin', 'tayfun-admin')], max_length=200, verbose_name='Personel')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Avans Tutarı')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
            ],
            options={
                'verbose_name': 'Avans Ödemesi',
                'verbose_name_plural': 'Avans Ödemeleri',
            },
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('comission_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Prim ID')),
                ('comission_code', models.CharField(default=Finance.models.Comission.generate_unique_code, max_length=8, verbose_name='Prim kodu')),
                ('type_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Komisyon Türü')),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Satış Fiyatı')),
                ('comission_rate', models.IntegerField(default=0, verbose_name='Komisyon Oranı (%)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Toplam')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
                ('user', models.CharField(choices=[('betul-admin', 'betul-admin'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-admin', 'tayfun-admin')], max_length=200, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Komisyon/Prim',
                'verbose_name_plural': 'Komisyonlar/Primler',
            },
        ),
        migrations.CreateModel(
            name='CompanyExpenseTable',
            fields=[
                ('table_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Tablo Kodu')),
            ],
            options={
                'verbose_name': 'Şirket Gider Girişi',
                'verbose_name_plural': 'Şirket Giderleri',
            },
        ),
        migrations.CreateModel(
            name='CompanyIncomeTable',
            fields=[
                ('table_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Tablo Kodu')),
            ],
            options={
                'verbose_name': 'Şirket Gelir Girişi',
                'verbose_name_plural': 'Şirket Gelirleri',
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('incentive_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Teşvik ID')),
                ('incentive_code', models.CharField(default=Finance.models.Incentive.generate_unique_code, max_length=8, verbose_name='Teşvik Kodu')),
                ('user', models.CharField(choices=[('betul-admin', 'betul-admin'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-admin', 'tayfun-admin')], max_length=200, verbose_name='Personel')),
                ('incentive_name', models.CharField(max_length=350, verbose_name='Konu')),
                ('incentive_amount', models.IntegerField(verbose_name='Teşvik Tutarı')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
            ],
            options={
                'verbose_name': 'Teşvik',
                'verbose_name_plural': 'Teşvikler',
            },
        ),
        migrations.CreateModel(
            name='PersonalExpenseTable',
            fields=[
                ('table_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Tablo Kodu')),
            ],
            options={
                'verbose_name': 'Bireysel Gider Girişi',
                'verbose_name_plural': 'Bireysel Giderler',
            },
        ),
        migrations.CreateModel(
            name='PersonalIncomeTable',
            fields=[
                ('table_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Tablo Kodu')),
            ],
            options={
                'verbose_name': 'Bireysel Gelir Girişi',
                'verbose_name_plural': 'Bireysel Gelirler',
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('punishment_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Ceza ID')),
                ('punishment_code', models.CharField(default=Finance.models.Punishment.generate_unique_code, max_length=8, verbose_name='Ceza Kodu')),
                ('user', models.CharField(choices=[('betul-admin', 'betul-admin'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-admin', 'tayfun-admin')], max_length=200, verbose_name='Personel')),
                ('punishment_topic', models.CharField(max_length=200, verbose_name='Başlık')),
                ('punishment_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Ceza Tutarı')),
                ('punishment_explanation', models.TextField(verbose_name='Açıklama')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
            ],
            options={
                'verbose_name': 'Ceza',
                'verbose_name_plural': 'Cezalar',
            },
        ),
        migrations.CreateModel(
            name='SalaryInfo',
            fields=[
                ('salary_info_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Salary Info ID')),
                ('salary_info_code', models.CharField(default=Finance.models.SalaryInfo.generate_unique_code, max_length=8, verbose_name='Maaş Kodu')),
                ('user', models.CharField(choices=[('betul-admin', 'betul-admin'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-admin', 'tayfun-admin')], max_length=200, verbose_name='Personel')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Maaş')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
            ],
            options={
                'verbose_name': 'Maaş',
                'verbose_name_plural': 'Maaşlar',
            },
        ),
        migrations.CreateModel(
            name='UnitName',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Birim ID')),
                ('unit_name', models.CharField(max_length=100, verbose_name='Birim Adı')),
            ],
            options={
                'verbose_name': 'Birim',
                'verbose_name_plural': 'Birimler',
            },
        ),
        migrations.CreateModel(
            name='PersonalIncome',
            fields=[
                ('income_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Gelir ID')),
                ('income_code', models.CharField(default=Finance.models.PersonalIncome.generate_unique_code, max_length=8, verbose_name='Gelir Kodu')),
                ('income_name', models.CharField(max_length=100, verbose_name='Gelir Adı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Miktar')),
                ('currency_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Döviz Fiyatı')),
                ('currency_type', models.CharField(choices=[('₺ (TRY)', '₺ (TRY)'), ('€ (EUR)', '€ (EUR)'), ('$ (USD)', '$ (USD)')], default='₺ (TRY)', max_length=15, verbose_name='Döviz Cinsi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Fiyat')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Ara Toplam')),
                ('vat_rate', models.IntegerField(default=0, verbose_name='KDV Oranı (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='KDV Tutarı')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Genel Toplam')),
                ('user', models.CharField(choices=[('betul-admin', 'betul-admin'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-admin', 'tayfun-admin')], max_length=200, verbose_name='Kullanıcı')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
                ('table_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.personalincometable', verbose_name='Giriş Bilgisi')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_units', to='Finance.unitname', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Bireysel Gelir',
                'verbose_name_plural': 'Bireysel Gelir Listesi',
            },
        ),
        migrations.CreateModel(
            name='PersonalExpenseForUserEntry',
            fields=[
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Gider ID')),
                ('expense_code', models.CharField(default=Finance.models.PersonalExpenseForUserEntry.generate_unique_code, max_length=8, verbose_name='Gider Kodu')),
                ('expense_name', models.CharField(max_length=100, verbose_name='Gider Adı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Miktar')),
                ('currency_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Döviz Fiyatı')),
                ('currency_type', models.CharField(choices=[('₺ (TRY)', '₺ (TRY)'), ('€ (EUR)', '€ (EUR)'), ('$ (USD)', '$ (USD)')], default='₺ (TRY)', max_length=15, verbose_name='Döviz Cinsi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Fiyat')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Ara Toplam')),
                ('vat_rate', models.IntegerField(default=0, verbose_name='KDV Oranı (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='KDV Tutarı')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Genel Toplam')),
                ('user', models.CharField(choices=[('betul-admin', 'betul-admin'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-admin', 'tayfun-admin')], max_length=50, verbose_name='Personel')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
                ('approval_status', models.CharField(choices=[('Onay Surecinde', 'Onay Sürecinde'), ('Onay', 'Onay'), ('Ret', 'Ret')], default='Onay Surecinde', max_length=50, verbose_name='Onay Durumu')),
                ('payment_status', models.CharField(choices=[('Odenmedi', 'Ödenmedi'), ('Odendi', 'Ödendi')], default='Odenmedi', max_length=120, verbose_name='Ödeme Durumu')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_for_user_entry_units', to='Finance.unitname', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Bireysel Gider Girişi',
                'verbose_name_plural': 'Bireysel Gider Girişleri',
            },
        ),
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Gider ID')),
                ('expense_code', models.CharField(default=Finance.models.PersonalExpense.generate_unique_code, max_length=8, verbose_name='Gider Kodu')),
                ('expense_name', models.CharField(max_length=100, verbose_name='Gider Adı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Miktar')),
                ('currency_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Döviz Fiyatı')),
                ('currency_type', models.CharField(choices=[('₺ (TRY)', '₺ (TRY)'), ('€ (EUR)', '€ (EUR)'), ('$ (USD)', '$ (USD)')], default='₺ (TRY)', max_length=15, verbose_name='Döviz Cinsi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Fiyat')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Ara Toplam')),
                ('vat_rate', models.IntegerField(default=0, verbose_name='KDV Oranı (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='KDV Tutarı')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Genel Toplam')),
                ('user', models.CharField(choices=[('betul-admin', 'betul-admin'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-admin', 'tayfun-admin')], max_length=200, verbose_name='Kullanıcı')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
                ('table_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.personalexpensetable', verbose_name='Giriş Bilgisi')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_units', to='Finance.unitname', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Bireysel Gider',
                'verbose_name_plural': 'Bireysel Gider Listesi',
            },
        ),
        migrations.CreateModel(
            name='CompanyIncome',
            fields=[
                ('income_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Gelir ID')),
                ('income_code', models.CharField(default=Finance.models.CompanyIncome.generate_unique_code, max_length=8, verbose_name='Gelir Kodu')),
                ('income_name', models.CharField(max_length=100, verbose_name='Gelir Adı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Miktar')),
                ('currency_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Döviz Fiyatı')),
                ('currency_type', models.CharField(choices=[('₺ (TRY)', '₺ (TRY)'), ('€ (EUR)', '€ (EUR)'), ('$ (USD)', '$ (USD)')], default='₺ (TRY)', max_length=15, verbose_name='Döviz Cinsi')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Fiyat')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Ara Toplam')),
                ('vat_rate', models.IntegerField(default=0, verbose_name='KDV Oranı (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='KDV Tutarı')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Genel Toplam')),
                ('payment_type', models.CharField(choices=[('Nakit', 'Nakit'), ('Kredi Kart', 'Kredi Kartı'), ('EFT/Havale', 'EFT/Havale'), ('Çek', 'Çek'), ('Senet', 'Senet'), ('Uluslararası Para Transferi', 'Uluslararası Para Transferi')], default='Nakit', max_length=200, verbose_name='Gelir Türü')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
                ('income_to', models.CharField(max_length=200, verbose_name='Kime/Nereye')),
                ('table_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.companyincometable', verbose_name='Giriş Bilgisi')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_income_units', to='Finance.unitname', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Şirket Geliri',
                'verbose_name_plural': 'Şirket Gelir Listesi',
            },
        ),
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Gelir ID')),
                ('expense_code', models.CharField(default=Finance.models.CompanyExpense.generate_unique_code, max_length=8, verbose_name='Gelir Kodu')),
                ('expense_name', models.CharField(max_length=100, verbose_name='Gelir Adı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Miktar')),
                ('currency_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Döviz Fiyatı')),
                ('currency_type', models.CharField(choices=[('₺ (TRY)', '₺ (TRY)'), ('€ (EUR)', '€ (EUR)'), ('$ (USD)', '$ (USD)')], default='₺ (TRY)', max_length=15, verbose_name='Döviz Cinsi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Fiyat')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Ara Toplam')),
                ('vat_rate', models.IntegerField(default=0, verbose_name='KDV Oranı (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='KDV Tutarı')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Genel Toplam')),
                ('payment_type', models.CharField(choices=[('Nakit', 'Nakit'), ('Kredi Kart', 'Kredi Kartı'), ('EFT/Havale', 'EFT/Havale'), ('Çek', 'Çek'), ('Senet', 'Senet'), ('Uluslararası Para Transferi', 'Uluslararası Para Transferi')], default='Nakit', max_length=200, verbose_name='Gider Türü')),
                ('log_date', models.DateField(default=datetime.date(2021, 8, 2), verbose_name='İşlem Tarihi')),
                ('expense_to', models.CharField(max_length=200, verbose_name='Kime/Nereye')),
                ('table_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.companyexpensetable', verbose_name='Giriş Bilgisi')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_expense_units', to='Finance.unitname', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Şirket Gideri',
                'verbose_name_plural': 'Şirket Gider Listesi',
            },
        ),
        migrations.CreateModel(
            name='CompanyExpenseSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Şirket Gider Özeti',
                'verbose_name_plural': 'Şirket Gider Özeti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Finance.companyexpense',),
        ),
        migrations.CreateModel(
            name='CompanyIncomeSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Şirket Gelir Özeti',
                'verbose_name_plural': 'Şirket Gelir Özeti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Finance.companyincome',),
        ),
        migrations.CreateModel(
            name='PersonalExpenseSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Bireysel Gider Özeti',
                'verbose_name_plural': 'Bireysel Gider Özeti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Finance.personalexpense',),
        ),
        migrations.CreateModel(
            name='PersonalIncomeSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Bireysel Gelir Özeti',
                'verbose_name_plural': 'Bireysel Gelir Özeti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Finance.personalincome',),
        ),
    ]
