# Generated by Django 3.1.7 on 2021-09-06 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_auto_20210902_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('Farzaneh', 'Farzaneh'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('TAYFUN.GUVEN', 'TAYFUN.GUVEN')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('Farzaneh', 'Farzaneh'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('TAYFUN.GUVEN', 'TAYFUN.GUVEN')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='companyexpense',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='companyincome',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('Farzaneh', 'Farzaneh'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('TAYFUN.GUVEN', 'TAYFUN.GUVEN')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('Farzaneh', 'Farzaneh'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('TAYFUN.GUVEN', 'TAYFUN.GUVEN')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='personalexpenseforuserentry',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalexpenseforuserentry',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('Farzaneh', 'Farzaneh'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('TAYFUN.GUVEN', 'TAYFUN.GUVEN')], max_length=50, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('Farzaneh', 'Farzaneh'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('TAYFUN.GUVEN', 'TAYFUN.GUVEN')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('Farzaneh', 'Farzaneh'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('TAYFUN.GUVEN', 'TAYFUN.GUVEN')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('Farzaneh', 'Farzaneh'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('TAYFUN.GUVEN', 'TAYFUN.GUVEN')], max_length=200, verbose_name='Personel'),
        ),
    ]
