# Generated by Django 3.1.7 on 2021-09-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0012_auto_20210913_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='user',
            field=models.CharField(choices=[('bayi-test', 'bayi-test'), ('betul-admin', 'betul-admin'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra-admin', 'mra-admin'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
    ]
