# Generated by Django 3.1.7 on 2021-09-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0018_auto_20210922_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('mha-mehmet', 'mha-mehmet'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('tayfun-guven', 'tayfun-guven')], max_length=200, verbose_name='Personel'),
        ),
    ]
