# Generated by Django 3.1.7 on 2021-10-05 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0026_auto_20211001_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('erkan-celikol', 'erkan-celikol'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('Isyap', 'Isyap'), ('Menasis', 'Menasis'), ('mha-mehmet', 'mha-mehmet'), ('Mmedya', 'Mmedya'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('serifozge', 'serifozge'), ('tayfun-guven', 'tayfun-guven'), ('TESTUSER', 'TESTUSER'), ('yaseminkesap', 'yaseminkesap')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('erkan-celikol', 'erkan-celikol'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('Isyap', 'Isyap'), ('Menasis', 'Menasis'), ('mha-mehmet', 'mha-mehmet'), ('Mmedya', 'Mmedya'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('serifozge', 'serifozge'), ('tayfun-guven', 'tayfun-guven'), ('TESTUSER', 'TESTUSER'), ('yaseminkesap', 'yaseminkesap')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='companyexpense',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='companyincome',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('erkan-celikol', 'erkan-celikol'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('Isyap', 'Isyap'), ('Menasis', 'Menasis'), ('mha-mehmet', 'mha-mehmet'), ('Mmedya', 'Mmedya'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('serifozge', 'serifozge'), ('tayfun-guven', 'tayfun-guven'), ('TESTUSER', 'TESTUSER'), ('yaseminkesap', 'yaseminkesap')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('erkan-celikol', 'erkan-celikol'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('Isyap', 'Isyap'), ('Menasis', 'Menasis'), ('mha-mehmet', 'mha-mehmet'), ('Mmedya', 'Mmedya'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('serifozge', 'serifozge'), ('tayfun-guven', 'tayfun-guven'), ('TESTUSER', 'TESTUSER'), ('yaseminkesap', 'yaseminkesap')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='personalexpenseforuserentry',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('erkan-celikol', 'erkan-celikol'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('Isyap', 'Isyap'), ('Menasis', 'Menasis'), ('mha-mehmet', 'mha-mehmet'), ('Mmedya', 'Mmedya'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('serifozge', 'serifozge'), ('tayfun-guven', 'tayfun-guven'), ('TESTUSER', 'TESTUSER'), ('yaseminkesap', 'yaseminkesap')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('erkan-celikol', 'erkan-celikol'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('Isyap', 'Isyap'), ('Menasis', 'Menasis'), ('mha-mehmet', 'mha-mehmet'), ('Mmedya', 'Mmedya'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('serifozge', 'serifozge'), ('tayfun-guven', 'tayfun-guven'), ('TESTUSER', 'TESTUSER'), ('yaseminkesap', 'yaseminkesap')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='user',
            field=models.CharField(choices=[('betul', 'betul'), ('erkan-celikol', 'erkan-celikol'), ('farzaneh.d', 'farzaneh.d'), ('hakan-aydogan', 'hakan-aydogan'), ('Isyap', 'Isyap'), ('Menasis', 'Menasis'), ('mha-mehmet', 'mha-mehmet'), ('Mmedya', 'Mmedya'), ('mra', 'mra'), ('Polokom', 'Polokom'), ('serifozge', 'serifozge'), ('tayfun-guven', 'tayfun-guven'), ('TESTUSER', 'TESTUSER'), ('yaseminkesap', 'yaseminkesap')], max_length=200, verbose_name='Personel'),
        ),
    ]
