# Generated by Django 3.2.8 on 2021-10-28 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0033_auto_20211025_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='user',
            field=models.CharField(choices=[('None', 'None')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='user',
            field=models.CharField(choices=[('None', 'None')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='companyexpense',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='companyincome',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='user',
            field=models.CharField(choices=[('None', 'None')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='user',
            field=models.CharField(choices=[('None', 'None')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='personalexpenseforuserentry',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='user',
            field=models.CharField(choices=[('None', 'None')], max_length=200, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='user',
            field=models.CharField(choices=[('None', 'None')], max_length=200, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='user',
            field=models.CharField(choices=[('None', 'None')], max_length=200, verbose_name='Personel'),
        ),
    ]
