# Generated by Django 3.2.9 on 2021-11-09 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0040_auto_20211108_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='comission',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='companyexpense',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='companyincome',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalexpenseforuserentry',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalincome',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='salaryinfo',
            name='log_date',
            field=models.DateField(default=datetime.date(2021, 11, 9), verbose_name='İşlem Tarihi'),
        ),
    ]
