# Generated by Django 3.1.7 on 2021-08-13 10:56

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('advance_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Avans İstek Kodu')),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Avans Miktarı')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now, help_text='Avansın çekilmek istenildiği tarih', verbose_name='İstek Tarihi')),
                ('advance_reason', models.TextField(blank=True, null=True, verbose_name='Neden')),
                ('approval_status', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Onaylandi', 'Onaylandı'), ('Reddedildi', 'Reddedildi')], default='Beklemede', max_length=100, verbose_name='Onay Durumu')),
                ('user', models.CharField(default=django.contrib.auth.models.User, max_length=50, verbose_name='Personel Bilgisi')),
            ],
            options={
                'verbose_name': 'Avans Talebi',
                'verbose_name_plural': 'Avans Talepleri',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedPerson',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('job_title', models.CharField(max_length=50, verbose_name='Ünvan')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('e_mail', models.CharField(max_length=100, verbose_name='E-posta')),
            ],
            options={
                'verbose_name': 'İlgili Kişi',
                'verbose_name_plural': 'İlgili Kişiler',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Firma adı')),
                ('business_field', models.CharField(max_length=150, verbose_name='İş alanı')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('website', models.CharField(blank=True, max_length=150, null=True, verbose_name='Websitesi')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='CompanyAuthorizedPerson',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('job_title', models.CharField(max_length=50, verbose_name='Ünvan')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('e_mail', models.CharField(max_length=100, verbose_name='E-posta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_authorizeds', to='Staff.company', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Firma Yetkilisi',
                'verbose_name_plural': 'Firma Yetkilileri',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Personel Kodu')),
                ('employee_name', models.CharField(max_length=50, verbose_name='İsim')),
                ('employee_surname', models.CharField(max_length=50, verbose_name='Soy İsim')),
                ('employee_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('employee_email', models.EmailField(max_length=254, verbose_name='E-Posta')),
            ],
            options={
                'verbose_name': 'Personel Kaydı',
                'verbose_name_plural': 'Personel Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='İş Türü')),
            ],
            options={
                'verbose_name': 'İş Türü',
                'verbose_name_plural': 'İş Türleri',
            },
        ),
        migrations.CreateModel(
            name='OldReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Rapor Kodu')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('report_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Rapor Tarihi')),
                ('user', models.CharField(default=django.contrib.auth.models.User, max_length=50, verbose_name='Personel Bilgisi')),
                ('communication_type', models.CharField(choices=[('Genel', 'Genel'), ('Telefon', 'Telefon'), ('E-posta', 'E-posta'), ('Toplanti (Online & Yuzyuze)', 'Toplantı (Online & Yüzyüze)'), ('Demo', 'Demo'), ('Egitim (Yuzyuze)', 'Eğitim (Yüzyüze)'), ('Egitim (Online)', 'Eğitim (Online)'), ('Etkinlik', 'Etkinlik'), ('Yazilim', 'Yazılım'), ('Tamir', 'Tamir')], max_length=150, verbose_name='İletişim Şekli')),
                ('company_status', models.CharField(choices=[('Eski', 'Eski'), ('Yeni', 'Yeni')], max_length=50, verbose_name='Şirket Statüsü')),
                ('company_name', models.CharField(max_length=200, verbose_name='Şirket Adı')),
                ('related_person', models.CharField(max_length=150, verbose_name='Görüşülen Kişi')),
                ('related_person_title', models.CharField(max_length=150, verbose_name='Kişinin Ünvanı')),
                ('related_person_phone', models.CharField(max_length=150, verbose_name='Telefon Numarası')),
                ('business_status', models.CharField(choices=[('Takipte', 'Takipte'), ('Tamamlanmis', 'Tamamlanmış'), ('Takipsiz', 'Takipsiz')], max_length=50, verbose_name='Durum')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('report_document', models.FileField(blank=True, null=True, upload_to='report_docs/', verbose_name='Ek Belge')),
            ],
            options={
                'verbose_name': 'Eski Günlük Rapor',
                'verbose_name_plural': 'Eski Günlük Raporlar',
            },
        ),
        migrations.CreateModel(
            name='PermitRequest',
            fields=[
                ('permit_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='İzin İstek Kodu')),
                ('date_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Başlangıç')),
                ('date_end', models.DateTimeField(default=datetime.datetime.now, verbose_name='Bitiş')),
                ('permit_choice', models.CharField(choices=[('Yillik Izin', 'Yıllık İzin'), ('Saglik Izni', 'Sağlık İzni'), ('Özel Izin', 'Özel İzin')], max_length=150, verbose_name='İzin Kategorisi')),
                ('permit_type', models.CharField(choices=[('Ücretli Izin', 'Ücretli İzin'), ('Ücretsiz Izin', 'Ücretsiz İzin')], max_length=100, verbose_name='İzin Türü')),
                ('permit_reason', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('approval_status', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Onaylandi', 'Onaylandı'), ('Reddedildi', 'Reddedildi')], default='Beklemede', max_length=100, verbose_name='Onay Durumu')),
                ('user', models.CharField(default=django.contrib.auth.models.User, max_length=50, verbose_name='Personel Bilgisi')),
                ('permit_document', models.FileField(blank=True, null=True, upload_to='permit_docs/', verbose_name='Ek Belge')),
            ],
            options={
                'verbose_name': 'İzin Talebi',
                'verbose_name_plural': 'İzin Talepleri',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Rapor Kodu')),
                ('user', models.CharField(default=django.contrib.auth.models.User, max_length=50, verbose_name='Personel Bilgisi')),
                ('report_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Rapor Tarihi')),
            ],
            options={
                'verbose_name': 'Günlük Rapor',
                'verbose_name_plural': 'Günlük Raporlar',
            },
        ),
        migrations.CreateModel(
            name='ReportContent',
            fields=[
                ('content_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('job_status', models.CharField(choices=[('Eski', 'Eski'), ('Yeni', 'Yeni')], max_length=50, verbose_name='İş Statüsü')),
                ('work_progress', models.CharField(choices=[('Takipte', 'Takipte'), ('Tamamlandi', 'Tamamlandı'), ('Takipsiz', 'Takipsiz')], max_length=100, verbose_name='İş durumu')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('report_document', models.FileField(blank=True, null=True, upload_to='report_docs/', verbose_name='Ek Belge')),
                ('company', models.ManyToManyField(blank=True, null=True, related_name='companies', to='Staff.Company', verbose_name='Firma')),
                ('company_authorized', models.ManyToManyField(blank=True, null=True, related_name='company_people', to='Staff.CompanyAuthorizedPerson', verbose_name='Firma Yetkilisi')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to='Staff.jobtype', verbose_name='İş Türü')),
                ('related_person', models.ManyToManyField(blank=True, null=True, related_name='authorized_people', to='Staff.AuthorizedPerson', verbose_name='İlgili Kişi')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Staff.report')),
            ],
            options={
                'verbose_name': 'Rapor İçeriği',
                'verbose_name_plural': '',
            },
        ),
    ]
