# Generated by Django 3.2.9 on 2021-12-23 07:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTask',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('state', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked')], default=('to_do', 'To Do'), max_length=200, verbose_name='State')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical', 'Critical')], default=('normal', 'Normal'), max_length=100, verbose_name='Priority')),
                ('description', models.TextField(verbose_name='Description')),
                ('attach', models.FileField(blank=True, null=True, upload_to='GENERAL/Business Task Folders/', verbose_name='Attach File')),
                ('assigned_to', models.ManyToManyField(related_name='business_users', to=settings.AUTH_USER_MODEL, verbose_name='Assign To')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='BusinessTaskComment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='Comment')),
                ('author', models.CharField(default=django.contrib.auth.models.User, max_length=50, verbose_name='From')),
                ('attach', models.FileField(blank=True, null=True, upload_to='GENERAL/Business Task Folders/', verbose_name='Attach File')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_tasks', to='Staff.businesstask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
