# Generated by Django 3.2.9 on 2021-12-23 08:45

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_businesstask_businesstaskcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstaskcomment',
            options={'verbose_name': 'Replied By', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterField(
            model_name='businesstaskcomment',
            name='comment',
            field=models.TextField(verbose_name=''),
        ),
        migrations.CreateModel(
            name='BusinessTaskChildComment',
            fields=[
                ('child_comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('child_comment', models.TextField(verbose_name='')),
                ('author', models.CharField(default=django.contrib.auth.models.User, max_length=50, verbose_name='From')),
                ('attach', models.FileField(blank=True, null=True, upload_to='GENERAL/Business Task Folders/', verbose_name='Attach File')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_tasks', to='Staff.businesstaskcomment', verbose_name='Parent Comment')),
            ],
            options={
                'verbose_name': 'Replied By',
                'verbose_name_plural': '',
            },
        ),
    ]
