# Generated by Django 3.1.7 on 2021-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_delete_oldreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizedperson',
            options={'verbose_name': 'Momento Medya İlgili', 'verbose_name_plural': 'Momento Medya İlgililer'},
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='related_person',
            field=models.ManyToManyField(blank=True, null=True, related_name='authorized_people', to='Staff.AuthorizedPerson', verbose_name='Momento Medya İlgili'),
        ),
    ]
