# Generated by Django 3.1.7 on 2021-10-20 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_auto_20210813_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.RemoveField(
            model_name='companyauthorizedperson',
            name='job_title',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default=1, max_length=300, verbose_name='Ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Firma Unvani'),
        ),
        migrations.AddField(
            model_name='company',
            name='e_mail',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-Posta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='has_invoice',
            field=models.BooleanField(blank=True, default=False, verbose_name='Fatura bilgisi'),
        ),
        migrations.AddField(
            model_name='company',
            name='official_address',
            field=models.TextField(blank=True, null=True, verbose_name='Resmi Adres'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_administration',
            field=models.TextField(blank=True, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vergi Numarasi'),
        ),
        migrations.AddField(
            model_name='companyauthorizedperson',
            name='authorized_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Unvan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default=1, verbose_name='Adres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Firma Kodu'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='companyauthorizedperson',
            name='e_mail',
            field=models.CharField(max_length=100, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='companyauthorizedperson',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='companyauthorizedperson',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='companyauthorizedperson',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon'),
        ),
    ]
