# Generated by Django 3.1.7 on 2021-10-20 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_auto_20211020_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon'),
        ),
    ]
