# Generated by Django 3.2.9 on 2021-12-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_alter_businesstaskchildcomment_parent_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstaskchildcomment',
            options={'verbose_name': 'Reply', 'verbose_name_plural': ''},
        ),
    ]
