# Generated by Django 3.1.7 on 2021-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_auto_20211020_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedperson',
            name='e_mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='authorizedperson',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon'),
        ),
    ]
