# Generated by Django 3.2.9 on 2021-12-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_alter_businesstask_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstaskcomment',
            options={'permissions': [('comment_add_permission', 'Add Comment Permission')], 'verbose_name': 'Replied By', 'verbose_name_plural': 'Replies'},
        ),
    ]
