# Generated by Django 3.2.9 on 2021-12-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0007_alter_businesstaskcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstaskcomment',
            name='comment',
            field=models.TextField(verbose_name='Reply'),
        ),
    ]
