# Generated by Django 3.1.7 on 2021-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModel', '0003_auto_20211020_1407'),
        ('Staff', '0008_company_mersis_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontent',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='GeneralModel.Firm', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='company_authorized',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_people', to='GeneralModel.FirmAuthorizedPerson', verbose_name='Firma Yetkilisi'),
        ),
    ]
