# Generated by Django 3.2.9 on 2021-12-27 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Staff', '0009_alter_businesstaskcomment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstaskchildcomment',
            options={'verbose_name': 'Replied By', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='businesstaskcomment',
            options={'verbose_name': 'Replied By', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AddField(
            model_name='businesstaskcomment',
            name='tag_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_relateds', to=settings.AUTH_USER_MODEL, verbose_name='Related Person'),
        ),
        migrations.AlterField(
            model_name='businesstaskchildcomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_tasks', to='Staff.businesstaskcomment', verbose_name='Parent Comment'),
        ),
        migrations.AlterField(
            model_name='businesstaskcomment',
            name='comment',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
