# Generated by Django 3.1.7 on 2021-10-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_auto_20211020_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyauthorizedperson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='companyauthorizedperson',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyAuthorizedPerson',
        ),
    ]
