# Generated by Django 3.2.9 on 2021-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0010_auto_20211020_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcontent',
            name='job_type',
        ),
        migrations.AddField(
            model_name='reportcontent',
            name='job_type',
            field=models.ManyToManyField(related_name='job_types', to='Staff.JobType', verbose_name='İş Türü'),
        ),
    ]
