# Generated by Django 3.2.9 on 2021-11-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0011_auto_20211110_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarReport',
            fields=[
            ],
            options={
                'verbose_name': 'Rapor',
                'verbose_name_plural': 'Raporlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Staff.reportcontent',),
        ),
    ]
