# Generated by Django 3.2.9 on 2021-11-18 14:10

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RMAApply',
            fields=[
                ('apply_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Basvuru Id')),
                ('customer_first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('customer_last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('customer_company', models.CharField(blank=True, max_length=300, null=True, verbose_name='Firma')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-Posta')),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('product_brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('product_model', models.CharField(max_length=500, verbose_name='Model')),
                ('product_serial', models.CharField(max_length=200, verbose_name='Cihaz Seri No')),
                ('apply_topic', models.CharField(max_length=500, verbose_name='Ariza Bildirisi Konusu')),
                ('problems', multiselectfield.db.fields.MultiSelectField(choices=[('hasarli_govde', 'Hasarli Govde'), ('hasarli_psu', 'Hasarli PSU'), ('hasarli_io_port', 'Hasarli I/O | Port'), ('hasarli_ekran_lcd', 'Hasarli Ekran | LCD'), ('hasarli_tus', 'Hasarli Tus'), ('diger', 'Diger')], max_length=77, verbose_name='Problem')),
                ('problem_note', models.TextField(verbose_name='Aciklama')),
                ('other_chechked', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tanim')),
                ('pdpb_approval', models.BooleanField(verbose_name='KVKK Onayi')),
            ],
            options={
                'verbose_name': 'RMA Basvurusu',
                'verbose_name_plural': 'RMA Basvurulari',
            },
        ),
    ]
