# Generated by Django 3.2.9 on 2021-12-14 10:20

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputName', models.CharField(max_length=100, verbose_name='İsim')),
                ('inputSurname', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('inputEmail', models.EmailField(max_length=254, verbose_name='E-Posta Adresi')),
                ('inputPhone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon Numarası')),
                ('inputMessage', models.TextField(verbose_name='Mesajınız')),
            ],
            options={
                'verbose_name': 'Career Page',
                'verbose_name_plural': 'Career Pages',
            },
        ),
        migrations.CreateModel(
            name='RMAApply',
            fields=[
                ('apply_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Basvuru Id')),
                ('customer_first_name', models.CharField(max_length=100, verbose_name='Adınız*')),
                ('customer_last_name', models.CharField(max_length=100, verbose_name='Soyadınız*')),
                ('customer_company', models.CharField(blank=True, max_length=300, null=True, verbose_name='Firma İsmi')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-Posta*')),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon Numarası*')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('product_brand', models.CharField(max_length=100, verbose_name='Marka*')),
                ('product_model', models.CharField(max_length=500, verbose_name='Model*')),
                ('product_serial', models.CharField(max_length=200, verbose_name='Cihaz Seri No*')),
                ('apply_topic', models.CharField(max_length=500, verbose_name='Ariza Bildirisi Konusu*')),
                ('problems', multiselectfield.db.fields.MultiSelectField(choices=[('hasarli_govde', 'Hasarli Govde'), ('hasarli_psu', 'Hasarli PSU'), ('hasarli_io_port', 'Hasarli I/O | Port'), ('hasarli_ekran_lcd', 'Hasarli Ekran | LCD'), ('hasarli_tus', 'Hasarli Tus'), ('diger', 'Diger')], max_length=77, verbose_name='Problem')),
                ('problem_note', models.TextField(verbose_name='Açıklama*')),
            ],
            options={
                'verbose_name': 'RMA Basvurusu',
                'verbose_name_plural': 'RMA Basvurulari',
            },
        ),
    ]
