# Generated by Django 3.2.9 on 2021-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('display', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('UYARI', 'UYARI'), ('HATA', 'HATA'), ('YENİ', 'YENİ'), ('BİLGİ', 'BİLGİ')], default='UYARI', max_length=7)),
            ],
        ),
    ]
