# Generated by Django 3.1.7 on 2021-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='level',
            field=models.CharField(choices=[('Warning', 'Warning'), ('Error', 'Error'), ('Success', 'Success'), ('Info', 'Info')], default='info', max_length=7),
        ),
    ]
