# Generated by Django 3.1.7 on 2021-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0002_auto_20210806_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='level',
            field=models.CharField(choices=[('UYARI', 'UYARI'), ('HATA', 'HATA'), ('YENİ', 'YENİ'), ('BİLGİ', 'BİLGİ')], default='UYARI', max_length=7),
        ),
    ]
