# Generated by Django 3.1.7 on 2021-10-20 10:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('firm_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Firma Kodu')),
                ('company_name', models.CharField(max_length=300, verbose_name='Ad')),
                ('business_field', models.CharField(max_length=150, verbose_name='İş alanı')),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('has_invoice', models.BooleanField(blank=True, default=False, verbose_name='Fatura bilgisi')),
                ('tax_administration', models.TextField(blank=True, null=True, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vergi Numarasi')),
                ('mersis_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mersis No')),
                ('company_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Firma Unvani')),
                ('official_address', models.TextField(blank=True, null=True, verbose_name='Resmi Adres')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='FirmAuthorizedPerson',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('authorized_title', models.CharField(max_length=50, verbose_name='Unvan')),
                ('phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon')),
                ('e_mail', models.CharField(max_length=100, null=True, verbose_name='E-posta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_authorizeds', to='GeneralModel.firm', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Firma Yetkilisi',
                'verbose_name_plural': 'Firma Yetkilileri',
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
