# Generated by Django 3.1.7 on 2021-10-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name': 'Sirket', 'verbose_name_plural': 'Sirketler'},
        ),
    ]
