# Generated by Django 3.1.7 on 2021-10-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModel', '0002_auto_20211020_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmauthorizedperson',
            options={'verbose_name': 'Sirket Yetkilisi', 'verbose_name_plural': 'Sirket Yetkilileri'},
        ),
    ]
