# Generated by Django 3.1.7 on 2021-10-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModel', '0003_auto_20211020_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('delivery_company_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Firma Kodu')),
                ('cargo_name', models.CharField(max_length=150, verbose_name='Teslimat Firması')),
                ('cargo_branch', models.CharField(blank=True, max_length=150, null=True, verbose_name='Teslimat Subesi')),
            ],
            options={
                'verbose_name': 'Teslimat Firması',
                'verbose_name_plural': 'Teslimat Firmaları',
            },
        ),
    ]
