# Generated by Django 3.2.9 on 2021-12-20 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0002_auto_20211216_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 12, 20), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 20), null=True, verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='rmaproduct',
            name='log_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 20), null=True, verbose_name='İşlem Tarihi'),
        ),
    ]
