# Generated by Django 3.1.7 on 2021-09-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0002_auto_20210901_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitycache',
            name='object_id',
            field=models.CharField(max_length=200, verbose_name='ID of the Object'),
        ),
    ]
