# Generated by Django 3.1.7 on 2021-09-01 12:57

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0003_auto_20210901_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenrty',
            name='unicode',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=200, verbose_name='Unicode'),
        ),
    ]
