# Generated by Django 3.2.9 on 2021-12-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0003_auto_20211220_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerComponentSoftware',
            fields=[
                ('component_software_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Software Id')),
                ('software_name', models.CharField(max_length=200, verbose_name='Yazilim')),
                ('software_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='Versiyon')),
            ],
            options={
                'verbose_name': 'Bilgisayar Yazilimi',
                'verbose_name_plural': 'Bilgisayar Yazilimlari',
            },
        ),
        migrations.CreateModel(
            name='CustomComputerComponent',
            fields=[
                ('custom_component_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Ozel Parca Id')),
                ('component', models.CharField(max_length=500, verbose_name='Özel Parça')),
            ],
            options={
                'verbose_name': 'Özel Parça',
                'verbose_name_plural': 'Özel Parçalar',
            },
        ),
        migrations.CreateModel(
            name='ComputerComponent',
            fields=[
                ('component_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Parca Id')),
                ('root', models.BooleanField(verbose_name='Root')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sifre')),
                ('hardware_id', models.CharField(max_length=100, verbose_name='Hardware Id')),
                ('case_info', models.CharField(max_length=500, verbose_name='Kasa')),
                ('cpu_info', models.CharField(max_length=500, verbose_name='CPU')),
                ('motherboard_info', models.CharField(max_length=500, verbose_name='Anakart')),
                ('random_access_memory_info', models.CharField(max_length=500, verbose_name='RAM')),
                ('harddiskdrive_info', models.CharField(max_length=500, verbose_name='HDD')),
                ('graphiccard_info', models.CharField(max_length=500, verbose_name='Ekran Karti')),
                ('custom_component', models.ManyToManyField(blank=True, null=True, related_name='custom_components', to='ProductSystem.CustomComputerComponent', verbose_name='Özel Parçalar')),
                ('software', models.ManyToManyField(blank=True, null=True, related_name='softwares', to='ProductSystem.ComputerComponentSoftware', verbose_name='Yazilimlar')),
            ],
            options={
                'verbose_name': 'Bilgisayar Bileseni',
                'verbose_name_plural': 'Bilgisayar Bilesenleri',
            },
        ),
        migrations.AddField(
            model_name='rmaproduct',
            name='computer_components',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='ProductSystem.computercomponent'),
        ),
    ]
