# Generated by Django 3.2.9 on 2021-12-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0004_auto_20211220_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='computercomponent',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP'),
        ),
    ]
