# Generated by Django 3.1.7 on 2021-09-06 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0006_auto_20210902_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycard',
            name='image_set',
            field=models.ManyToManyField(blank=True, null=True, related_name='ic_images', to='ProductSystem.InventoryCardImageSet', verbose_name='Görsel Seti'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ProductSystem.productcategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ürün Kodu'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='technical_info',
            field=models.TextField(blank=True, null=True, verbose_name='Teknik Bilgiler'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='İşlem Tarihi'),
        ),
    ]
