# Generated by Django 3.1.7 on 2021-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0009_auto_20210910_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Tavsiye Edilen Birim Fiyatı'),
        ),
    ]
