# Generated by Django 3.1.7 on 2021-09-16 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0011_auto_20210913_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycard',
            name='datasheet_document',
            field=models.FileField(blank=True, null=True, upload_to='PRODUCT DATASHEETS', verbose_name='Datasheet'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 9, 16), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(default=datetime.date(2021, 9, 16), verbose_name='İşlem Tarihi'),
        ),
    ]
