# Generated by Django 3.1.7 on 2021-09-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0013_auto_20210916_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycard',
            name='image_set',
        ),
        migrations.AddField(
            model_name='inventorycard',
            name='image_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ic_images', to='ProductSystem.inventorycardimageset', verbose_name='Görsel Seti'),
        ),
    ]
