# Generated by Django 3.1.7 on 2021-09-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0014_auto_20210916_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenrty',
            name='company_authorized',
            field=models.ManyToManyField(blank=True, null=True, related_name='entry_company_authorizeds', to='ProductSystem.CompanyAuthorizedPerson', verbose_name='Firma Yetkilisi'),
        ),
    ]
