# Generated by Django 3.1.7 on 2021-09-17 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0015_auto_20210916_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycard',
            name='image_set',
        ),
        migrations.AddField(
            model_name='inventorycard',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='InventoryCard/Images', verbose_name='Görsel 4'),
        ),
        migrations.AddField(
            model_name='inventorycard',
            name='image_one',
            field=models.ImageField(default=1, upload_to='InventoryCard/Images', verbose_name='Görsel 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorycard',
            name='image_tree',
            field=models.ImageField(blank=True, null=True, upload_to='InventoryCard/Images', verbose_name='Görsel 3'),
        ),
        migrations.AddField(
            model_name='inventorycard',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='InventoryCard/Images', verbose_name='Görsel 2'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 9, 17), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(default=datetime.date(2021, 9, 17), verbose_name='İşlem Tarihi'),
        ),
    ]
