# Generated by Django 3.1.7 on 2021-09-20 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0016_auto_20210917_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycard',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='InventoryCard/Images', verbose_name='Görsel 1'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 9, 20), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(default=datetime.date(2021, 9, 20), verbose_name='İşlem Tarihi'),
        ),
    ]
