# Generated by Django 3.1.7 on 2021-09-22 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0019_auto_20210921_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cihaz Adı'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 9, 22), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(default=datetime.date(2021, 9, 22), verbose_name='İşlem Tarihi'),
        ),
    ]
