# Generated by Django 3.1.7 on 2021-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0021_auto_20210922_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productidentification',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='InventoryID/Images', verbose_name='Görsel 4'),
        ),
        migrations.AlterField(
            model_name='productidentification',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='InventoryID/Images', verbose_name='Görsel 1'),
        ),
        migrations.AlterField(
            model_name='productidentification',
            name='image_tree',
            field=models.ImageField(blank=True, null=True, upload_to='InventoryID/Images', verbose_name='Görsel 3'),
        ),
        migrations.AlterField(
            model_name='productidentification',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='InventoryID/Images', verbose_name='Görsel 2'),
        ),
    ]
