# Generated by Django 3.1.7 on 2021-09-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0022_auto_20210922_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entry', to='ProductSystem.inventorycard', verbose_name='Stok Kartı'),
        ),
    ]
