# Generated by Django 3.1.7 on 2021-09-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0024_inventory_money_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='money_unit',
            field=models.CharField(blank=True, choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=10, null=True, verbose_name='Para Birimi'),
        ),
    ]
