# Generated by Django 3.1.7 on 2021-09-27 11:47

import ProductSystem.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0026_auto_20210923_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenrty',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=ProductSystem.models.ProductEnrty.user_directory_path, verbose_name='Görsel 2'),
        ),
        migrations.AddField(
            model_name='productenrty',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=ProductSystem.models.ProductEnrty.user_directory_path, verbose_name='Görsel 3'),
        ),
        migrations.AddField(
            model_name='productenrty',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=ProductSystem.models.ProductEnrty.user_directory_path, verbose_name='Görsel 4'),
        ),
        migrations.AddField(
            model_name='productenrty',
            name='money_unit',
            field=models.CharField(blank=True, choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=10, null=True, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='productoutlet',
            name='money_unit',
            field=models.CharField(blank=True, choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=10, null=True, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 9, 27), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='image',
            field=models.ImageField(upload_to=ProductSystem.models.ProductEnrty.user_directory_path, verbose_name='Görsel 1'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(default=datetime.date(2021, 9, 27), verbose_name='İşlem Tarihi'),
        ),
    ]
