# Generated by Django 3.1.7 on 2021-09-28 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0027_auto_20210927_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 9, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(default=datetime.date(2021, 9, 28), verbose_name='İşlem Tarihi'),
        ),
    ]
