# Generated by Django 3.1.7 on 2021-09-28 07:38

import ProductSystem.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0029_auto_20210928_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoutlet',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_companies', to='ProductSystem.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='company_authorized',
            field=models.ManyToManyField(blank=True, null=True, related_name='outlet_company_authorizeds', to='ProductSystem.CompanyAuthorizedPerson', verbose_name='Firma Yetkilisi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 28), null=True, verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_interval',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ne Kadar Duracak'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='deliverer',
            field=models.ManyToManyField(blank=True, null=True, related_name='outlet_deliverers', to='ProductSystem.Deliverer', verbose_name='Teslimat Yapan Kişi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='delivery_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_delivery_companies', to='ProductSystem.deliverycompany', verbose_name='Teslimat Yapan Firma'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='departure_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_reasons', to='ProductSystem.departurereason', verbose_name='Gidiş Nedeni'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ProductSystem.models.ProductOutlet.user_directory_path, verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_outlet', to='ProductSystem.inventory', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Adet'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Fiyat'),
        ),
    ]
