# Generated by Django 3.1.7 on 2021-09-28 07:39

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0030_auto_20210928_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoutlet',
            name='unicode',
            field=models.CharField(default=django.utils.crypto.get_random_string, editable=False, max_length=1000, verbose_name='Unicode'),
        ),
    ]
