# Generated by Django 3.1.7 on 2021-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0033_inventory_warehouse_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='shelf_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Raf No'),
        ),
    ]
