# Generated by Django 3.1.7 on 2021-09-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0034_auto_20210928_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productidentification',
            options={'verbose_name': 'Urun Kimligi', 'verbose_name_plural': 'Urun Kimlikleri'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entry', to='ProductSystem.inventorycard', verbose_name='Stok Kartı'),
            preserve_default=False,
        ),
    ]
