# Generated by Django 3.1.7 on 2021-09-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0035_auto_20210928_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entry', to='ProductSystem.inventorycard', verbose_name='Stok Kartı'),
        ),
    ]
