# Generated by Django 3.1.7 on 2021-09-30 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0037_auto_20210929_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('custom_permission', 'Custom View Permission')], 'verbose_name': 'Envanter Kaydı', 'verbose_name_plural': 'Envanter'},
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 9, 30), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 30), null=True, verbose_name='İşlem Tarihi'),
        ),
    ]
