# Generated by Django 3.1.7 on 2021-09-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0038_auto_20210930_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='warehouse_info',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='InventoryCard/Images', verbose_name='Gorsel'),
        ),
    ]
