# Generated by Django 3.1.7 on 2021-09-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0039_auto_20210930_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='warehouse_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ids_warehouse_infos', to='ProductSystem.warehouseinfo', verbose_name='Depo Bilgileri'),
        ),
    ]
