# Generated by Django 3.1.7 on 2021-10-01 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0040_inventory_warehouse_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorycard',
            old_name='image_tree',
            new_name='image_three',
        ),
        migrations.RenameField(
            model_name='inventorycardimageset',
            old_name='image_tree',
            new_name='image_three',
        ),
        migrations.RenameField(
            model_name='inventoryimages',
            old_name='image_tree',
            new_name='image_three',
        ),
        migrations.RenameField(
            model_name='productidentificationimages',
            old_name='image_tree',
            new_name='image_three',
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 10, 1), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 1), null=True, verbose_name='İşlem Tarihi'),
        ),
    ]
