# Generated by Django 3.1.7 on 2021-10-07 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0042_auto_20211005_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productenrty',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productenrty',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productenrty',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productenrty',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productenrty',
            name='product_id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_entry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entry', to='ProductSystem.productenrty'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_companies', to='ProductSystem.company', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 10, 7), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 7), null=True, verbose_name='İşlem Tarihi'),
        ),
    ]
