# Generated by Django 3.1.7 on 2021-10-15 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0043_auto_20211007_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoutlet',
            name='has_serial',
            field=models.BooleanField(blank=True, default=True, verbose_name='Dahili ile ara'),
        ),
        migrations.AddField(
            model_name='productoutlet',
            name='product_id_inv',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_outlet_id', to='ProductSystem.Inventory', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 10, 15), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 15), null=True, verbose_name='İşlem Tarihi'),
        ),
        migrations.RemoveField(
            model_name='productoutlet',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productoutlet',
            name='product_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_outlet_id', to='ProductSystem.ProductIdentification', verbose_name='Ürün'),
        ),
    ]
