# Generated by Django 3.1.7 on 2021-10-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModel', '0003_auto_20211020_1407'),
        ('ProductSystem', '0048_auto_20211020_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenrty',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_companies', to='GeneralModel.firm', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='company_authorized',
            field=models.ManyToManyField(blank=True, null=True, related_name='entry_company_authorizeds', to='GeneralModel.FirmAuthorizedPerson', verbose_name='Firma Yetkilisi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_companies', to='GeneralModel.firm', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='company_authorized',
            field=models.ManyToManyField(blank=True, null=True, related_name='outlet_company_authorizeds', to='GeneralModel.FirmAuthorizedPerson', verbose_name='Firma Yetkilisi'),
        ),
    ]
