# Generated by Django 3.1.7 on 2021-10-25 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0050_auto_20211020_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 10, 25), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 25), null=True, verbose_name='İşlem Tarihi'),
        ),
        migrations.RemoveField(
            model_name='productoutlet',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productoutlet',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_outlet_id', to='ProductSystem.productidentification', verbose_name='Ürün Dahili No'),
        ),
        migrations.RemoveField(
            model_name='productoutlet',
            name='product_id_inv',
        ),
        migrations.AddField(
            model_name='productoutlet',
            name='product_id_inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_outlet_id', to='ProductSystem.inventory', verbose_name='Ürün Adi'),
        ),
    ]
