# Generated by Django 3.2.8 on 2021-10-28 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0051_auto_20211025_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productenrty',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='productenrty',
            name='date_arrival',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='date_departure',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 28), null=True, verbose_name='İşlem Tarihi'),
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('sub_category_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Kategori Kodu')),
                ('sub_category_name', models.CharField(max_length=150, verbose_name='Kategori Adı')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='ProductSystem.productcategory', verbose_name='Ana Kategori')),
            ],
            options={
                'verbose_name': 'Alt Kategori',
                'verbose_name_plural': 'Alt Kategoriler',
            },
        ),
        migrations.AddField(
            model_name='inventorycard',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='ProductSystem.productsubcategory', verbose_name='Alt Kategori'),
        ),
    ]
