# Generated by Django 3.2.8 on 2021-11-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0054_auto_20211102_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_sub_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Kategori'),
        ),
    ]
