# Generated by Django 3.2.8 on 2021-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0055_inventory_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenrty',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Adet'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_sub_category',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt Kategori'),
        ),
    ]
