# Generated by Django 3.2.9 on 2021-11-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0061_auto_20211109_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryCardImageSet',
        ),
        migrations.RemoveField(
            model_name='inventoryimages',
            name='inventory_id',
        ),
        migrations.DeleteModel(
            name='ProductIdentificationImages',
        ),
        migrations.DeleteModel(
            name='InventoryImages',
        ),
    ]
