# Generated by Django 3.2.9 on 2021-11-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0062_auto_20211109_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='warehouse_info',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entry', to='ProductSystem.inventorycard', verbose_name='Stok Kartı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='image_one',
            field=models.ImageField(default=1, upload_to='InventoryCard/Images', verbose_name='Görsel 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='product_code',
            field=models.CharField(default='REVIEW!', max_length=1000, verbose_name='Ürün Kodu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='product_name',
            field=models.CharField(default='REVIEW!', max_length=1000, verbose_name='Ürün Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='departure_reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure_reasons', to='ProductSystem.departurereason', verbose_name='Gidiş Nedeni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoutlet',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Fiyat'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WarehouseInfo',
        ),
    ]
