# Generated by Django 3.2.9 on 2021-11-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0066_calendarreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarReport',
        ),
    ]
