# Generated by Django 3.2.9 on 2021-11-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0072_auto_20211118_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_datasheet',
            field=models.FileField(blank=True, null=True, upload_to='PRODUCT DATASHEETS', verbose_name='Datasheet'),
        ),
    ]
