# Generated by Django 3.2.9 on 2021-12-14 08:06

import ProjectForm.models
import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Bayi ID')),
                ('dealer_name', models.CharField(max_length=200, verbose_name='Bayi')),
            ],
            options={
                'verbose_name': 'Bayi',
                'verbose_name_plural': 'Bayiler',
            },
        ),
        migrations.CreateModel(
            name='RegisterDeal',
            fields=[
                ('is_displayed', models.BooleanField(default=False, verbose_name='Herkese açık olarak gösterilsin mi?')),
                ('deal_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Proje ID')),
                ('project_name', models.CharField(max_length=250, unique=True, verbose_name='Proje Adı')),
                ('project_subject', models.CharField(max_length=250, verbose_name='Proje Konusu')),
                ('approval', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('bosta', 'Boşta')], default='beklemede', max_length=20, verbose_name='Onay Durumu')),
                ('project_date', models.DateField(default=datetime.date(2021, 12, 14), verbose_name='Proje Tarihi')),
                ('estimated_date', models.DateField(validators=[ProjectForm.models.RegisterDeal.validate_date, ProjectForm.models.RegisterDeal.validate_initial_date], verbose_name='Tahmini Teslim Tarihi')),
                ('project_time', models.IntegerField(verbose_name='Proje Süresi')),
                ('manager_note', models.TextField(verbose_name='Açıklama (Momento Medya)')),
                ('user', models.CharField(default=django.contrib.auth.models.User, max_length=100, verbose_name='Düzenleyen')),
                ('project_status', models.CharField(choices=[('takipte', 'Takipte'), ('tamamlandi', 'Tamamlandı'), ('takipsiz', 'Takipsiz'), ('iptal', 'İptal')], default='takipte', max_length=150, verbose_name='İlerleme Durumu')),
                ('project_description', models.TextField(verbose_name='Açıklama')),
                ('company', models.CharField(max_length=150, verbose_name='Kurum Adı')),
                ('company_address', models.TextField(verbose_name='Kurum Adresi')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('contact_surname', models.CharField(max_length=150, verbose_name='Soyad')),
                ('contact_phone', models.CharField(default='+', help_text='+ÜLKEKODU5555555555', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon')),
                ('contact_email', models.CharField(max_length=150, verbose_name='E-posta')),
            ],
            options={
                'verbose_name': 'Proje Kaydı',
                'verbose_name_plural': 'Proje Kayıtlarım',
            },
        ),
        migrations.CreateModel(
            name='RegisterLogs',
            fields=[
                ('is_displayed', models.BooleanField(verbose_name='Herkese açık olarak gösterilsin mi?')),
                ('log_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Proje ID')),
                ('project_name', models.CharField(max_length=250, verbose_name='Proje Adı')),
                ('project_subject', models.CharField(max_length=250, verbose_name='Proje Konusu')),
                ('approval', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('bosta', 'Boşta')], default='beklemede', max_length=20, verbose_name='Onay Durumu')),
                ('project_date', models.DateField(verbose_name='Proje Tarihi')),
                ('estimated_date', models.DateField(verbose_name='Tahmini Teslim Tarihi')),
                ('project_time', models.IntegerField(verbose_name='Proje Süresi')),
                ('manager_note', models.TextField(blank=True, null=True, verbose_name='Açıklama (Momento Medya)')),
                ('user', models.CharField(default=django.contrib.auth.models.User, max_length=100, verbose_name='Düzenleyen')),
                ('project_status', models.CharField(choices=[('takipte', 'Takipte'), ('tamamlandi', 'Tamamlandı'), ('takipsiz', 'Takipsiz'), ('iptal', 'İptal')], default='takipte', max_length=150, verbose_name='İlerleme Durumu')),
                ('project_description', models.TextField(verbose_name='Açıklama')),
                ('company', models.CharField(max_length=150, verbose_name='Kurum Adı')),
                ('company_address', models.TextField(verbose_name='Kurum Adresi')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('contact_surname', models.CharField(max_length=150, verbose_name='Soyad')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('contact_email', models.CharField(max_length=150, verbose_name='E-posta')),
            ],
            options={
                'verbose_name': 'Proje Güncelleme Listesi',
                'verbose_name_plural': 'Proje Güncellemeleri Listesi',
            },
        ),
        migrations.CreateModel(
            name='InventoryForDealer',
            fields=[
            ],
            options={
                'verbose_name': 'Momento Medya Envanter',
                'verbose_name_plural': 'Momento Medya Envanter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductSystem.inventory',),
        ),
        migrations.CreateModel(
            name='DealerUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Bayi ID')),
                ('user', models.CharField(default=django.contrib.auth.models.User, max_length=200, verbose_name='Kullanıcı')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='ProjectForm.dealer', verbose_name='Bayi')),
            ],
            options={
                'verbose_name': 'Bayi Kullanıcısı',
                'verbose_name_plural': 'Bayi Kullanıcıları',
            },
        ),
        migrations.CreateModel(
            name='DealerProjectSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Tüm Bayi Projeleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProjectForm.registerlogs',),
        ),
    ]
