# Generated by Django 3.2.9 on 2021-12-16 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 12, 16), verbose_name='Proje Tarihi'),
        ),
    ]
