# Generated by Django 3.1.7 on 2021-08-20 11:25

import ProjectForm.models
import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0002_auto_20210818_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterLogs',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Proje ID')),
                ('project_name', models.CharField(max_length=250, verbose_name='Proje Adı')),
                ('project_subject', models.CharField(max_length=250, verbose_name='Proje Konusu')),
                ('approval', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20, verbose_name='Onay Durumu')),
                ('project_date', models.DateField(verbose_name='Proje Tarihi')),
                ('estimated_date', models.DateField(verbose_name='Tahmini Teslim Tarihi')),
                ('project_time', models.IntegerField(verbose_name='Proje Süresi')),
                ('manager_note', models.TextField(blank=True, null=True, verbose_name='Açıklama (Momento Medya)')),
                ('user', models.CharField(default=django.contrib.auth.models.User, max_length=100, verbose_name='Düzenleyen')),
                ('project_status', models.CharField(choices=[('takipte', 'Takipte'), ('tamamlandi', 'Tamamlandı'), ('takipsiz', 'Takipsiz'), ('iptal', 'İptal')], default='takipte', max_length=150, verbose_name='İlerleme Durumu')),
                ('project_description', models.TextField(verbose_name='Açıklama')),
                ('company', models.CharField(max_length=150, verbose_name='Kurum Adı')),
                ('company_address', models.TextField(verbose_name='Kurum Adresi')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('contact_surname', models.CharField(max_length=150, verbose_name='Soyad')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('contact_email', models.CharField(max_length=150, verbose_name='E-posta')),
            ],
            options={
                'verbose_name': 'Proje Güncellemesi',
                'verbose_name_plural': 'Proje Güncellemeleri',
            },
        ),
        migrations.AddField(
            model_name='registerdeal',
            name='approval',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20, verbose_name='Onay Durumu'),
        ),
        migrations.AddField(
            model_name='registerdeal',
            name='manager_note',
            field=models.TextField(default=1, verbose_name='Açıklama (Momento Medya)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerdeal',
            name='project_subject',
            field=models.CharField(default=1, max_length=250, verbose_name='Proje Konusu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerdeal',
            name='estimated_date',
            field=models.DateField(validators=[ProjectForm.models.RegisterDeal.validate_date], verbose_name='Tahmini Teslim Tarihi'),
        ),
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 8, 20), verbose_name='Proje Tarihi'),
        ),
        migrations.AlterField(
            model_name='registerdeal',
            name='project_status',
            field=models.CharField(choices=[('takipte', 'Takipte'), ('tamamlandi', 'Tamamlandı'), ('takipsiz', 'Takipsiz'), ('iptal', 'İptal')], default='takipte', max_length=150, verbose_name='İlerleme Durumu'),
        ),
    ]
