# Generated by Django 3.1.7 on 2021-08-20 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0003_auto_20210820_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='contact_phone',
            field=models.CharField(default='+', help_text='+9XXXXXXXXXXX', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+9XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon'),
        ),
    ]
