# Generated by Django 3.1.7 on 2021-09-06 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0006_auto_20210902_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='approval',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('bosta', 'Boşta')], default='beklemede', max_length=20, verbose_name='Onay Durumu'),
        ),
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 6), verbose_name='Proje Tarihi'),
        ),
        migrations.AlterField(
            model_name='registerlogs',
            name='approval',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('bosta', 'Boşta')], default='beklemede', max_length=20, verbose_name='Onay Durumu'),
        ),
    ]
