# Generated by Django 3.1.7 on 2021-09-10 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0007_auto_20210906_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 10), verbose_name='Proje Tarihi'),
        ),
    ]
