# Generated by Django 3.1.7 on 2021-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSystem', '0010_inventory_recommended_price'),
        ('ProjectForm', '0008_auto_20210910_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryForDealer',
            fields=[
            ],
            options={
                'verbose_name': 'Momento Medya Envanter',
                'verbose_name_plural': 'Momento Medya Envanter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductSystem.inventory',),
        ),
        migrations.AlterField(
            model_name='registerdeal',
            name='project_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Proje Adı'),
        ),
    ]
