# Generated by Django 3.1.7 on 2021-09-13 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0009_auto_20210910_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 13), verbose_name='Proje Tarihi'),
        ),
    ]
