# Generated by Django 3.1.7 on 2021-09-16 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0010_auto_20210913_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 16), verbose_name='Proje Tarihi'),
        ),
    ]
