# Generated by Django 3.1.7 on 2021-09-17 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0011_auto_20210916_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 17), verbose_name='Proje Tarihi'),
        ),
    ]
