# Generated by Django 3.1.7 on 2021-09-20 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0012_auto_20210917_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 20), verbose_name='Proje Tarihi'),
        ),
    ]
