# Generated by Django 3.1.7 on 2021-09-22 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0014_auto_20210921_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 22), verbose_name='Proje Tarihi'),
        ),
    ]
