# Generated by Django 3.1.7 on 2021-09-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0016_registerdeal_is_displayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdeal',
            name='is_displayed',
        ),
        migrations.AddField(
            model_name='registerlogs',
            name='is_displayed',
            field=models.BooleanField(default=False, verbose_name='Gösterim Durumu'),
        ),
    ]
