# Generated by Django 3.1.7 on 2021-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0018_auto_20210922_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlogs',
            name='is_displayed',
            field=models.BooleanField(verbose_name='Herkese açık olarak gösterilsin mi?'),
        ),
    ]
