# Generated by Django 3.1.7 on 2021-09-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0019_auto_20210922_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealerprojectsummary',
            options={'verbose_name': 'Proje', 'verbose_name_plural': 'Tüm Bayi Projeleri'},
        ),
        migrations.AlterModelOptions(
            name='registerlogs',
            options={'verbose_name': 'Proje Güncelleme Listesi', 'verbose_name_plural': 'Proje Güncellemeleri Listesi'},
        ),
    ]
