# Generated by Django 3.1.7 on 2021-09-23 09:05

import ProjectForm.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0020_auto_20210922_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerdeal',
            options={'verbose_name': 'Proje Kaydı', 'verbose_name_plural': 'Proje Kayıtlarım'},
        ),
        migrations.AlterField(
            model_name='registerdeal',
            name='contact_phone',
            field=models.CharField(default='+', help_text='+ÜLKEKODU5555555555', max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon formatı '+XXXXXXXXXXX' şeklinde olmalıdır!", regex='^\\+?1?\\d{9,13}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='registerdeal',
            name='estimated_date',
            field=models.DateField(validators=[ProjectForm.models.RegisterDeal.validate_date, ProjectForm.models.RegisterDeal.validate_initial_date], verbose_name='Tahmini Teslim Tarihi'),
        ),
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 23), verbose_name='Proje Tarihi'),
        ),
    ]
