# Generated by Django 3.1.7 on 2021-09-27 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0021_auto_20210923_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 27), verbose_name='Proje Tarihi'),
        ),
    ]
