# Generated by Django 3.1.7 on 2021-09-28 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0022_auto_20210927_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 28), verbose_name='Proje Tarihi'),
        ),
    ]
