# Generated by Django 3.1.7 on 2021-09-29 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0023_auto_20210928_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 29), verbose_name='Proje Tarihi'),
        ),
    ]
