# Generated by Django 3.1.7 on 2021-09-30 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0024_auto_20210929_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 9, 30), verbose_name='Proje Tarihi'),
        ),
    ]
