# Generated by Django 3.1.7 on 2021-10-01 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0025_auto_20210930_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 10, 1), verbose_name='Proje Tarihi'),
        ),
    ]
