# Generated by Django 3.1.7 on 2021-10-05 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0026_auto_20211001_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 10, 5), verbose_name='Proje Tarihi'),
        ),
    ]
