# Generated by Django 3.1.7 on 2021-10-07 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0027_auto_20211005_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 10, 7), verbose_name='Proje Tarihi'),
        ),
    ]
