# Generated by Django 3.1.7 on 2021-10-19 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0030_auto_20211018_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 10, 19), verbose_name='Proje Tarihi'),
        ),
    ]
