# Generated by Django 3.1.7 on 2021-10-20 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0031_auto_20211019_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 10, 20), verbose_name='Proje Tarihi'),
        ),
    ]
