# Generated by Django 3.1.7 on 2021-10-25 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0032_auto_20211020_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 10, 25), verbose_name='Proje Tarihi'),
        ),
    ]
