# Generated by Django 3.2.8 on 2021-10-28 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectForm', '0033_auto_20211025_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdeal',
            name='project_date',
            field=models.DateField(default=datetime.date(2021, 10, 28), verbose_name='Proje Tarihi'),
        ),
    ]
